/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LearningPathService } from "../learningPath.service";
import { LearningPathCreateInput } from "./LearningPathCreateInput";
import { LearningPath } from "./LearningPath";
import { LearningPathFindManyArgs } from "./LearningPathFindManyArgs";
import { LearningPathWhereUniqueInput } from "./LearningPathWhereUniqueInput";
import { LearningPathUpdateInput } from "./LearningPathUpdateInput";
import { ProgressFindManyArgs } from "../../progress/base/ProgressFindManyArgs";
import { Progress } from "../../progress/base/Progress";
import { ProgressWhereUniqueInput } from "../../progress/base/ProgressWhereUniqueInput";

export class LearningPathControllerBase {
  constructor(protected readonly service: LearningPathService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LearningPath })
  async createLearningPath(
    @common.Body() data: LearningPathCreateInput
  ): Promise<LearningPath> {
    return await this.service.createLearningPath({
      data: {
        ...data,

        instructor: data.instructor
          ? {
              connect: data.instructor,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        instructor: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [LearningPath] })
  @ApiNestedQuery(LearningPathFindManyArgs)
  async learningPaths(@common.Req() request: Request): Promise<LearningPath[]> {
    const args = plainToClass(LearningPathFindManyArgs, request.query);
    return this.service.learningPaths({
      ...args,
      select: {
        createdAt: true,
        id: true,

        instructor: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LearningPath })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async learningPath(
    @common.Param() params: LearningPathWhereUniqueInput
  ): Promise<LearningPath | null> {
    const result = await this.service.learningPath({
      where: params,
      select: {
        createdAt: true,
        id: true,

        instructor: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LearningPath })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLearningPath(
    @common.Param() params: LearningPathWhereUniqueInput,
    @common.Body() data: LearningPathUpdateInput
  ): Promise<LearningPath | null> {
    try {
      return await this.service.updateLearningPath({
        where: params,
        data: {
          ...data,

          instructor: data.instructor
            ? {
                connect: data.instructor,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          instructor: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LearningPath })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLearningPath(
    @common.Param() params: LearningPathWhereUniqueInput
  ): Promise<LearningPath | null> {
    try {
      return await this.service.deleteLearningPath({
        where: params,
        select: {
          createdAt: true,
          id: true,

          instructor: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/progresses")
  @ApiNestedQuery(ProgressFindManyArgs)
  async findProgresses(
    @common.Req() request: Request,
    @common.Param() params: LearningPathWhereUniqueInput
  ): Promise<Progress[]> {
    const query = plainToClass(ProgressFindManyArgs, request.query);
    const results = await this.service.findProgresses(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        learner: {
          select: {
            id: true,
          },
        },

        learningPath: {
          select: {
            id: true,
          },
        },

        progressPercentage: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/progresses")
  async connectProgresses(
    @common.Param() params: LearningPathWhereUniqueInput,
    @common.Body() body: ProgressWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      progresses: {
        connect: body,
      },
    };
    await this.service.updateLearningPath({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/progresses")
  async updateProgresses(
    @common.Param() params: LearningPathWhereUniqueInput,
    @common.Body() body: ProgressWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      progresses: {
        set: body,
      },
    };
    await this.service.updateLearningPath({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/progresses")
  async disconnectProgresses(
    @common.Param() params: LearningPathWhereUniqueInput,
    @common.Body() body: ProgressWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      progresses: {
        disconnect: body,
      },
    };
    await this.service.updateLearningPath({
      where: params,
      data,
      select: { id: true },
    });
  }
}
