/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ReadingStatistics as PrismaReadingStatistics,
  Learner as PrismaLearner,
  LearningResource as PrismaLearningResource,
} from "@prisma/client";

export class ReadingStatisticsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ReadingStatisticsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.readingStatistics.count(args);
  }

  async readingStatisticsItems(
    args: Prisma.ReadingStatisticsFindManyArgs
  ): Promise<PrismaReadingStatistics[]> {
    return this.prisma.readingStatistics.findMany(args);
  }
  async readingStatistics(
    args: Prisma.ReadingStatisticsFindUniqueArgs
  ): Promise<PrismaReadingStatistics | null> {
    return this.prisma.readingStatistics.findUnique(args);
  }
  async createReadingStatistics(
    args: Prisma.ReadingStatisticsCreateArgs
  ): Promise<PrismaReadingStatistics> {
    return this.prisma.readingStatistics.create(args);
  }
  async updateReadingStatistics(
    args: Prisma.ReadingStatisticsUpdateArgs
  ): Promise<PrismaReadingStatistics> {
    return this.prisma.readingStatistics.update(args);
  }
  async deleteReadingStatistics(
    args: Prisma.ReadingStatisticsDeleteArgs
  ): Promise<PrismaReadingStatistics> {
    return this.prisma.readingStatistics.delete(args);
  }

  async getLearner(parentId: string): Promise<PrismaLearner | null> {
    return this.prisma.readingStatistics
      .findUnique({
        where: { id: parentId },
      })
      .learner();
  }

  async getLearningResource(
    parentId: string
  ): Promise<PrismaLearningResource | null> {
    return this.prisma.readingStatistics
      .findUnique({
        where: { id: parentId },
      })
      .learningResource();
  }
}
